Punctuation joined the match
Capitals joined the match
Lowercase joined the match
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
CAPITALS: Great pass!
CAPITALS: Nice shot!
LOWERCASE: Great pass!
LOWERCASE: Nice shot!
PUNCTUATION: Take the shot!
PUNCTUATION: No problem.
PUNCTUATION: I got it!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
CAPITALS: Take the shot!
CAPITALS: No problem.
CAPITALS: I got it!
CAPITALS: Great pass!
CAPITALS: Take the shot!
CAPITALS: No problem.
CAPITALS: I got it!
CAPITALS: Nice shot!
CAPITALS: Nice shot!
CAPITALS: Defending...
CAPITALS: What a save!
CAPITALS: Defending...
CAPITALS: What a save!
LOWERCASE: Take the shot!
LOWERCASE: No problem.
LOWERCASE: I got it!
LOWERCASE: Great pass!
LOWERCASE: Take the shot!
LOWERCASE: No problem.
LOWERCASE: I got it!
LOWERCASE: Nice shot!
LOWERCASE: Nice shot!
LOWERCASE: Nice shot!
LOWERCASE: Defending...
LOWERCASE: What a save!
LOWERCASE: Defending...
LOWERCASE: What a save!
PUNCTUATION: Defending...
PUNCTUATION: What a save!
PUNCTUATION: I got it!
CAPITALS: I got it!
CAPITALS: I got it!
LOWERCASE: I got it!
LOWERCASE: I got it!
CAPITALS: Nice shot!
CAPITALS: Nice shot!
CAPITALS: Calculated.
helper joined the match
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Great pass!
LOWERCASE: No problem.
LOWERCASE: No problem.
LOWERCASE: No problem.
LOWERCASE: No problem.
LOWERCASE: Calculated.
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Calculated.
HELPER: Calculated.
The_L joined the match
THE_L: Nice shot!
THE_L: Nice shot!
THE_L: Nice shot!
THE_L: Great pass!
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Calculated.
PUNCTUATION: Nice shot!
PUNCTUATION: Nice shot!
PUNCTUATION: Calculated.
CAPITALS: I got it!
CAPITALS: Great pass!
CAPITALS: Take the shot!
CAPITALS: No problem.
CAPITALS: No problem.
CAPITALS: Defending...
CAPITALS: Nice shot!
CAPITALS: I got it!
CAPITALS: What a save!
CAPITALS: Defending...
CAPITALS: No problem.
CAPITALS: Calculated.
HELPER: Calculated.
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Nice shot!
HELPER: Calculated.
helper left the match
THE_L: Calculated.
The_L left the match
LOWERCASE: No problem.
LOWERCASE: Calculated.
PUNCTUATION: Nice shot!
PUNCTUATION: Calculated.
Capitals left the match
Lowercase left the match
Punctuation left the match